In [2]:
import numpy as np
import cv2

In [3]:
from cv2 import imshow, imread, imshow, IMREAD_GRAYSCALE

In [4]:
from cv2 import imread, imwrite, imshow, IMREAD_GRAYSCALE, namedWindow, waitKey, destroyAllWindows

In [5]:
from cv2 import IMREAD_GRAYSCALE

In [6]:
import sys

In [8]:
sys.version

'3.7.12 (default, Sep 10 2021, 00:20:04) \n[GCC 9.3.0]'

In [9]:
img = cv2.imread('task2.png', IMREAD_GRAYSCALE)

In [7]:
img

array([[254, 255, 255, ..., 251, 252, 255],
       [255, 255, 236, ..., 247, 253, 254],
       [255, 246, 205, ..., 213, 230, 247],
       ...,
       [215, 187, 184, ..., 199, 235, 254],
       [228, 204, 179, ..., 212, 246, 255],
       [234, 228, 209, ..., 236, 255, 254]], dtype=uint8)

In [56]:
img.shape

(442, 700)

In [59]:
filter_img = np.empty([0,img.shape[1]], dtype='uint8')
pad_top = np.array(np.zeros([1, img.shape[1]], dtype='uint8'))
# pad_top = np.array(np.zeros([1, img.shape[1]]))
pad_img = np.append(pad_top, img, axis=0)
pad_img = np.append(pad_img, pad_top, axis=0)
pad_left = np.array(np.zeros([pad_img.shape[0],1], dtype='uint8'))
# pad_left = np.array(np.zeros([pad_img.shape[0],1]))
pad_img = np.append(pad_left, pad_img, axis=1)
pad_img = np.append(pad_img, pad_left, axis=1)

In [64]:
pad_img.shape
# pad_img

(444, 702)

In [68]:
for i in range(1, pad_img.shape[0]-1):
    row = []
    for j in range(1, pad_img.shape[1]-1):
        med_filter = pad_img[i-1:i+2, j-1:j+2]
        row.append(np.median(med_filter))
    row = np.array(row, dtype='uint8')
    row = row.reshape(1,row.shape[0])
    filter_img = np.append(filter_img, row, axis=0)

In [74]:
# for i in range(1, pad_img.shape[0]):
#     print(i)
new = pad_img[0:3, 0:3]

In [75]:
new

array([[  0,   0,   0],
       [  0, 254, 255],
       [  0, 255, 255]], dtype=uint8)

In [77]:
np.flip(new)

array([[255, 255,   0],
       [255, 254,   0],
       [  0,   0,   0]], dtype=uint8)

In [84]:
new_img = np.pad(img, (1,1), 'constant', constant_values=(0,0))

In [105]:
new_img

array([[  0,   0,   0, ...,   0,   0,   0],
       [  0, 254, 255, ..., 252, 255,   0],
       [  0, 255, 255, ..., 253, 254,   0],
       ...,
       [  0, 228, 204, ..., 246, 255,   0],
       [  0, 234, 228, ..., 255, 254,   0],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=uint8)

In [85]:
new_img.shape

(444, 702)

In [51]:
np.empty([0,4])

array([], shape=(0, 4), dtype=float64)

In [104]:
normal = cv2.imread('results/task2_denoise1.jpg', IMREAD_GRAYSCALE)
short = cv2.imread('results/task2_denoise.jpg', IMREAD_GRAYSCALE)
arr = np.array([1,2,3,4,5,6])
brr = arr.copy()
x = brr == arr
x = normal == short
# print(type(x[1]))
for val in x:
#     print(val)
#     print(val.all())
    if bool(val.all()) is not True:
        print(1)
# arr = arr.reshape(1,arr.shape[0])
# arr.shape
# np.append(arr,brr, axis=)
# arr = np.array([1.0,2.0,3.0,4.0], 'uint8')
# arr.dtype

In [9]:
arr = np.array([1,2,3,4,5,6])
brr = arr.copy()
brr[1] = 1
x = brr == arr
print(x.all())

False


In [15]:
# a = a.reshape((9))
a.shape == b.shape

False

In [11]:
a = np.arange(9).reshape(3,3)
b = a.copy()

In [125]:
a,b

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]))

In [129]:
sum(a[1]*b[1])

50

In [130]:
np.inner(a[1],b[1])

50

In [123]:
a[1,1]

4

In [ ]:
np.all()

In [70]:
cv2.imwrite('abc.jpg',filter_img)

True

In [6]:
img1 = cv2.imread('task2.png')

In [7]:
img1

array([[[254, 254, 254],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [251, 251, 251],
        [252, 252, 252],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [236, 236, 236],
        ...,
        [247, 247, 247],
        [253, 253, 253],
        [254, 254, 254]],

       [[255, 255, 255],
        [246, 246, 246],
        [205, 205, 205],
        ...,
        [213, 213, 213],
        [230, 230, 230],
        [247, 247, 247]],

       ...,

       [[215, 215, 215],
        [187, 187, 187],
        [184, 184, 184],
        ...,
        [199, 199, 199],
        [235, 235, 235],
        [254, 254, 254]],

       [[228, 228, 228],
        [204, 204, 204],
        [179, 179, 179],
        ...,
        [212, 212, 212],
        [246, 246, 246],
        [255, 255, 255]],

       [[234, 234, 234],
        [228, 228, 228],
        [209, 209, 209],
        ...,
        [236, 236, 236],
        [255, 255, 255],
        [254, 254, 254]]

In [10]:
cv2.imwrite('abc.jpg',img1[:,:,2])

True

In [8]:
np.sqrt(3**2 + 4**2)

5.0

In [11]:
img1[0]

array([[254, 254, 254],
       [255, 255, 255],
       [255, 255, 255],
       ...,
       [251, 251, 251],
       [252, 252, 252],
       [255, 255, 255]], dtype=uint8)

In [35]:
img3 = cv2.imread('task3.png', IMREAD_GRAYSCALE)

In [36]:
img3

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [37]:
import pandas as pd

In [38]:
df = pd.DataFrame(img3)

In [15]:
df.value_counts()

0    1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57   58   59   60   61   62   63   64   65   66   67   68   69   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92   93   94   95   96   97   98   99   100  101  102  103  104  105  106  107  108  109  110  111  112  113  114  115  116  117  118  119  120  121  122  123  124  125  126  127  128  129  130  131  132  133  134  135  136  137  138  139  140  141  142  143  144  145  146  147  148  149  150  151  152  153  154  155  156  157  158  159  160  161  162  163  164  165  166  167  168  169  170  171  172  173  174  175  176  177  178  179  180  181  182  183  184  185  186  187  188  189  190  191  192  193  194  195  196  197  198  199  200  201  202  203  204  205  206  207  208  209  210  211  212  

In [16]:
a = np.ones([3,3], dtype='int')

In [17]:
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [18]:
b = a.copy()

In [19]:
b[0][1] = 0

In [28]:
if False in (a==b):
    print('done')

done


In [31]:
type(a==b)

numpy.ndarray

In [10]:
img = imread('task3.png', IMREAD_GRAYSCALE)

In [13]:
def morph_erode(img):
    """
    :param img: numpy.ndarray(int or bool), image
    :return erode_img: numpy.ndarray(int or bool), image, same size as the input image

    Apply mophology erosion on input binary image. 
    Use 3x3 squared structuring element of all 1's. 
    """
    # TO DO: implement your solution here
    filter = np.array([1,1,1,1,1,1,1,1,1], dtype='int').reshape([3,3])
    pad_img = np.pad(img, (1,1), 'constant', constant_values=(0,0))
    erode_img = np.ones(img.shape, dtype='int')
    for i in range(1,pad_img.shape[0]-1):
        for j in range(1,pad_img.shape[1]-1):
            mat = pad_img[i-1:i+2, j-1:j+2]
            if False in (filter == mat):
                erode_img[i-1][j-1] = 0
    print(erode_img)
#     imwrite('results/erode.jpg', erode_img)

In [14]:
morph_erode(img)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [36]:
img

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [49]:
filter = np.ones([3,3], dtype='uint8')

In [51]:
filter[1,1] == 1

True

In [20]:
img[0:3,0:3]

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint8)

In [32]:
not np.all(filter==img[0:3,0:3])

True

In [49]:
filter

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [1]:
filter

filter

In [16]:
type(img.shape)

tuple

In [48]:
df == 255

0      1      2      3      4      5      6      7      8      9    \
0    False  False  False  False  False  False  False  False  False  False   
1    False  False  False  False  False  False  False  False  False  False   
2    False  False  False  False  False  False  False  False  False  False   
3    False  False  False  False  False  False  False  False  False  False   
4    False  False  False  False  False  False  False  False  False  False   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
495  False  False  False  False  False  False  False  False  False  False   
496  False  False  False  False  False  False  False  False  False  False   
497  False  False  False  False  False  False  False  False  False  False   
498  False  False  False  False  False  False  False  False  False  False   
499  False  False  False  False  False  False  False  False  False  False   

     ...    490    491    492    493    494    495    496    497    498    499  
0    ...  False  False  False  False  False  False  False  False  False  False  
1    ...  False  False  False  False  False  False  False  False  False  False  
2    ...  False  False  False  False  False  False  False  False  False  False  
3    ...  False  False  False  False  False  False  False  False  False  False  
4    ...  False  False  False  False  False  False  False  False  False  False  
..   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  
495  ...  False  False  False  False  False  False  False  False  False  False  
496  ...  False  False  False  False  False  False  False  False  False  False  
497  ...  False  False  False  False  False  False  False  False  False  False  
498  ...  False  False  False  False  False  False  False  False  False  False  
499  ...  False  False  False  False  False  False  False  False  False  False  

[500 rows x 500 columns]

In [52]:
a = np.ones([3,3])
b = a.copy()
a = a*3

In [46]:
import time

In [55]:
a-b

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [7]:
left_img = cv2.imread('left.jpg')
right_img = cv2.imread('right.jpg')

In [8]:
left_img = cv2.cvtColor(left_img, cv2.COLOR_BGR2GRAY)
right_img = cv2.cvtColor(right_img, cv2.COLOR_BGR2GRAY)

In [14]:
sift = cv2.xfeatures2d.SIFT_create()
kp1, des1 = sift.detectAndCompute(left_img, None)
kp2, des2 = sift.detectAndCompute(right_img, None)

In [15]:
kp_left[0].pt

(2.389120578765869, 445.5633239746094)

In [41]:
((des1[1] - des2[1])**2).sum()

194200.0

In [44]:
def calc_ssd(des1, des2):
    left_ssd = np.zeros([des1.shape[0], des2.shape[0]])
    right_ssd = np.zeros([des2.shape[0], des1.shape[0]])
    for i in range(des1.shape[0]):
        for j in range(des2.shape[0]):
            ssd = ((des1[i]-des2[j]) ** 2).sum()
            left_ssd[i,j] = ssd
            right_ssd[j,i] = ssd
    print(left_ssd, right_ssd)

In [45]:
calc_ssd(des1, des2)

[[366210. 220199. 255008. ... 246536. 305845. 321645.]
 [313285. 194200. 285055. ... 264305. 271320. 380220.]
 [325822. 307883. 258340. ... 258466. 349031. 385097.]
 ...
 [297518. 294833. 352572. ... 206040. 269085. 275235.]
 [370073. 254136. 299557. ... 342891. 351746. 359594.]
 [226573. 332064. 227989. ... 346065. 283900. 312098.]] [[366210. 313285. 325822. ... 297518. 370073. 226573.]
 [220199. 194200. 307883. ... 294833. 254136. 332064.]
 [255008. 285055. 258340. ... 352572. 299557. 227989.]
 ...
 [246536. 264305. 258466. ... 206040. 342891. 346065.]
 [305845. 271320. 349031. ... 269085. 351746. 283900.]
 [321645. 380220. 385097. ... 275235. 359594. 312098.]]


In [47]:
t1 = time.time()
left_ssd = np.zeros([des1.shape[0], des2.shape[0]])
right_ssd = np.zeros([des2.shape[0], des1.shape[0]])
for i in range(des1.shape[0]):
    for j in range(des2.shape[0]):
        ssd = ((des1[i]-des2[j]) ** 2).sum()
        left_ssd[i,j] = ssd
        right_ssd[j,i] = ssd
t2 = time.time()
print(t2-t1)

126.09230065345764


In [ ]:
top

In [70]:
left_ssd[0].min()

10.0

In [67]:
min1_index = left_ssd[0].copy()
min1_index

array([1.00000e+01, 2.20199e+05, 2.55008e+05, ..., 2.46536e+05,
       3.05845e+05, 3.21645e+05])

In [68]:
min1_index[0] = 20

In [69]:
left_ssd[0][0]

10.0

In [53]:
min1_value = left_ssd[0][min1_index]
min1_value

108676.0

In [61]:
left_ssd[0][min1_index] = np.inf
min2_index = left_ssd[0].argmin()
min2_value = left_ssd[0][min2_index]

In [62]:
min2_value

111603.0

In [60]:
np.infty

inf

In [94]:
def find_nearest(left_ssd, right_ssd):
    left_d1 = {}
    right_d1 = {}
    for i in range(left_ssd.shape[0]):
        row = left_ssd[i]
        min1 = row.min()
        min1_ind = row.argmin()
        row[min1_ind] = np.infty
        min2 = row.min()
        min2_ind = row.argmin()
        row[min1_ind] = min1
        left_d1[i] = [min1_ind, min2_ind, min1, min2]
    for i in range(right_ssd.shape[0]):
        row = right_ssd[i]
        min1 = row.min()
        min1_ind = row.argmin()
        row[min1_ind] = np.infty
        min2 = row.min()
        min2_ind = row.argmin()
        row[min1_ind] = min1
        right_d1[i] = [min1_ind, min2_ind, min1, min2]
    return left_d1, right_d1

In [73]:
def calc_ssd(des1, des2):
    t1 = time.time()
    left_ssd = np.zeros([des1.shape[0], des2.shape[0]])
    right_ssd = np.zeros([des2.shape[0], des1.shape[0]])
    for i in range(des1.shape[0]):
        for j in range(des2.shape[0]):
            ssd = ((des1[i]-des2[j]) ** 2).sum()
            left_ssd[i,j] = ssd
            right_ssd[j,i] = ssd
    t2 = time.time()
    print('time consume in calc_ssd',t2-t1)
    return left_ssd, right_ssd

In [95]:
d1, d2 = find_nearest(left_ssd, right_ssd)
# row = left_ssd[0]

In [131]:
def potential_match(left_d1, right_d1):    #dictionary containing nearest matches in this case 2
    potential_match = {}
    for key in left_d1.keys():
        if right_d1[left_d1[key][0]][0] == key and right_d1[left_d1[key][1]][1] == key:
            potential_match[key] = left_d1[key]
    return potential_match

In [133]:
potential_d1 = potential_match(d1, d2)

In [134]:
len(potential_d1)

358

In [127]:
def final_match(potential_d):   #potential_d: dictionary contains valid match
    final_d = {}
    for key in potential_d.keys():
        val = potential_d[key]
        if val[2]/val[3] < 0.7:
            final_d[key] = potential_d[key]
    return final_d

In [137]:
final_d2 = final_match(potential_d2)

In [138]:
len(final_d2)

195

In [109]:
len(potential_d2)

1803

In [83]:
row[3350] = np.infty

TypeError: 'float' object is not callable

In [74]:
left_ssd, right_ssd = calc_ssd(des1, des2)
find_nearest(left_ssd, right_ssd)

time consume in calc_ssd 122.4777603149414


TypeError: 'float' object is not callable

In [86]:
d1, d2

({0: [108676.0, 111603.0, 3350, 4333],
  1: [105915.0, 107773.0, 3886, 3320],
  2: [96137.0, 104204.0, 727, 4343],
  3: [75844.0, 88328.0, 885, 849],
  4: [96089.0, 107144.0, 3697, 2336],
  5: [99305.0, 108271.0, 2858, 2598],
  6: [112531.0, 117879.0, 4099, 2439],
  7: [103985.0, 106354.0, 1661, 2710],
  8: [87930.0, 94421.0, 2557, 721],
  9: [125965.0, 127331.0, 1073, 1387],
  10: [130806.0, 131965.0, 1584, 500],
  11: [92851.0, 104768.0, 675, 2404],
  12: [107958.0, 107992.0, 2680, 3177],
  13: [126248.0, 133688.0, 2252, 4190],
  14: [72957.0, 73710.0, 503, 4262],
  15: [116672.0, 120815.0, 600, 2205],
  16: [89310.0, 101880.0, 1643, 3852],
  17: [80538.0, 98965.0, 2169, 1847],
  18: [107677.0, 116310.0, 1911, 2918],
  19: [93215.0, 98819.0, 2295, 502],
  20: [112607.0, 120018.0, 2828, 1662],
  21: [99308.0, 114178.0, 4249, 3290],
  22: [103213.0, 110704.0, 215, 2839],
  23: [111183.0, 114498.0, 3949, 3380],
  24: [51135.0, 63547.0, 3306, 3283],
  25: [56538.0, 75903.0, 2743, 2261],
