In [1]:
import numpy as np
import cv2

In [2]:
from cv2 import imshow, imread, imshow, IMREAD_GRAYSCALE

In [9]:
from cv2 import imread, imwrite, imshow, IMREAD_GRAYSCALE, namedWindow, waitKey, destroyAllWindows

In [3]:
from cv2 import IMREAD_GRAYSCALE

In [4]:
import sys

In [5]:
sys.version

'3.7.12 (default, Sep 10 2021, 00:20:04) \n[GCC 9.3.0]'

In [6]:
img = cv2.imread('task2.png', IMREAD_GRAYSCALE)

In [7]:
img

array([[254, 255, 255, ..., 251, 252, 255],
       [255, 255, 236, ..., 247, 253, 254],
       [255, 246, 205, ..., 213, 230, 247],
       ...,
       [215, 187, 184, ..., 199, 235, 254],
       [228, 204, 179, ..., 212, 246, 255],
       [234, 228, 209, ..., 236, 255, 254]], dtype=uint8)

In [10]:
img.shape

(442, 700)

In [27]:
pad_top = np.array(np.zeros([1, img.shape[1]], dtype='uint8'))
# pad_top = np.array(np.zeros([1, img.shape[1]]))
pad_img = np.append(pad_top, img, axis=0)
pad_img = np.append(pad_img, pad_top, axis=0)
pad_left = np.array(np.zeros([pad_img.shape[0],1], dtype='uint8'))
# pad_left = np.array(np.zeros([pad_img.shape[0],1]))
pad_img = np.append(pad_left, pad_img, axis=1)
pad_img = np.append(pad_img, pad_left, axis=1)

In [30]:
pad_img.shape
pad_img

array([[  0,   0,   0, ...,   0,   0,   0],
       [  0, 254, 255, ..., 252, 255,   0],
       [  0, 255, 255, ..., 253, 254,   0],
       ...,
       [  0, 228, 204, ..., 246, 255,   0],
       [  0, 234, 228, ..., 255, 254,   0],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=uint8)

In [31]:
for i in range(1, pad_img.shape[0]):
    for j in range(1, pad_img.shape[1]):
        med_filter = pad_img[i-1:i+2, j-1:j+2]
        print(med_filter.min())

<function ndarray.view>

In [6]:
img1 = cv2.imread('task2.png')

In [7]:
img1

array([[[254, 254, 254],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [251, 251, 251],
        [252, 252, 252],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [236, 236, 236],
        ...,
        [247, 247, 247],
        [253, 253, 253],
        [254, 254, 254]],

       [[255, 255, 255],
        [246, 246, 246],
        [205, 205, 205],
        ...,
        [213, 213, 213],
        [230, 230, 230],
        [247, 247, 247]],

       ...,

       [[215, 215, 215],
        [187, 187, 187],
        [184, 184, 184],
        ...,
        [199, 199, 199],
        [235, 235, 235],
        [254, 254, 254]],

       [[228, 228, 228],
        [204, 204, 204],
        [179, 179, 179],
        ...,
        [212, 212, 212],
        [246, 246, 246],
        [255, 255, 255]],

       [[234, 234, 234],
        [228, 228, 228],
        [209, 209, 209],
        ...,
        [236, 236, 236],
        [255, 255, 255],
        [254, 254, 254]]

In [10]:
cv2.imwrite('abc.jpg',img1[:,:,2])

True

In [11]:
img1[0]

array([[254, 254, 254],
       [255, 255, 255],
       [255, 255, 255],
       ...,
       [251, 251, 251],
       [252, 252, 252],
       [255, 255, 255]], dtype=uint8)